### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by buildrt** [HRMAssociation/About#1]
**輪廻転生RT**

**我将从事爆裂魔法的研究**

**我对爆裂魔法非常感兴趣**

**Additional context**
我宣誓：  
- [x] 尊重并遵守所在地区的法律
- [x] 尊重每个魔法成果的授权协议
- [x] 认同每个人都有学习、使用、开发和分享魔法的自由
- [x] 抵制对公开法术的收费分享
- [x] 热爱魔法，但不歧视麻瓜

**Comment by tumuyan** [comment]
已发送邀请函
