### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Winter-of-Cirno** [HRMAssociation/About#2]
**Name**
你的名字，可以有别于github账户名，会在特定场合优先使用
Winter-of-Cirno

**What do you want to do**
你来做什么
研究、贡献魔法技术

**What magic you're interested in**
你对哪些魔法技术感兴趣
声音魔法、像素魔法

**Additional context**
我宣誓：  
- [x] 尊重并遵守所在地区的法律
- [x] 尊重每个魔法成果的授权协议
- [x] 认同每个人都有学习、使用、开发和分享魔法的自由
- [x] 抵制对公开法术的收费分享
- [x] 热爱魔法，但不歧视麻瓜

**Comment by tumuyan** [comment]
已发送邀请函
